name: create task from template

on:
#   schedule:
#     - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: create issues from template
        run: |
            $issue_list=`gh issue list -l template --json title,body`
            IFS=$'\n'; for issue in $(echo $issue_list | jq -c '.[]'); do
              echo $issue | jq .name
            done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        